python gcc_search.py benchmark://chstone-v0/adpcm &
python gcc_search.py benchmark://chstone-v0/aes &
python gcc_search.py benchmark://chstone-v0/blowfish &
python gcc_search.py benchmark://chstone-v0/dfadd &
python gcc_search.py benchmark://chstone-v0/dfdiv &
python gcc_search.py benchmark://chstone-v0/dfmul &
python gcc_search.py benchmark://chstone-v0/dfsin &
python gcc_search.py benchmark://chstone-v0/gsm &
python gcc_search.py benchmark://chstone-v0/jpeg &
python gcc_search.py benchmark://chstone-v0/mips &
python gcc_search.py benchmark://chstone-v0/motion &
python gcc_search.py benchmark://chstone-v0/sha &
